NodeOUs:
  Enable: true
  ClientOUIdentifier: 
    Certificate: cacerts/localhost-2054-ca-holder.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-2054-ca-holder.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-2054-ca-holder.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-2054-ca-holder.pem
    OrganizationalUnitIdentifier: orderer
