NodeOUs:
  Enable: true
  ClientOUIdentifier: 
    Certificate: cacerts/localhost-1054-ca-issuer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-1054-ca-issuer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-1054-ca-issuer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-1054-ca-issuer.pem
    OrganizationalUnitIdentifier: orderer
